image: node:latest

before_script:
  - npm config set prefix /usr/local
  - npm install -g serverless
  - npm install
deploy-test:
  stage: deploy
  variables:
    STAGE: "test"
  script:
    - chmod u+x deploy-viveo-lambda.ci.sh
    - STAGE=$STAGE ./deploy-viveo-lambda.ci.sh
  environment: test
  only:
    - test-env
deploy-production:
  stage: deploy
  variables:
    STAGE: "production"
  script:
    - chmod u+x deploy-viveo-lambda.ci.sh
    - STAGE=$STAGE ./deploy-viveo-lambda.ci.sh
  environment: production
  only:
    - production-env
